# SPDX-FileCopyrightText: 2023 Shun Sakai
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

[tool.bumpversion]
current_version = "0.4.0"

[[tool.bumpversion.files]]
filename = "crates/capi/examples/meson.build"

[[tool.bumpversion.files]]
filename = "crates/capi/examples/version.hpp"

[[tool.bumpversion.files]]
filename = "crates/capi/src/lib.rs"

[[tool.bumpversion.files]]
glob = "docs/man/man3/*.3.adoc"
