# SPDX-FileCopyrightText: 2023 Shun Sakai
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

[tool.bumpversion]
current_version = "0.3.2"

[[tool.bumpversion.files]]
filename = "crates/capi/examples/meson.build"

[[tool.bumpversion.files]]
filename = "crates/capi/examples/version.hpp"

[[tool.bumpversion.files]]
filename = "crates/capi/src/lib.rs"
