# SPDX-FileCopyrightText: 2023 Shun Sakai
#
# SPDX-License-Identifier: GPL-3.0-or-later

[target.aarch64-unknown-linux-musl]
pre-build = ["apt-get update && apt-get install -y asciidoctor"]

[target.arm-unknown-linux-musleabihf]
pre-build = ["apt-get update && apt-get install -y asciidoctor"]

[target.armv7-unknown-linux-musleabihf]
pre-build = ["apt-get update && apt-get install -y asciidoctor"]

[target.x86_64-unknown-linux-musl]
pre-build = ["apt-get update && apt-get install -y asciidoctor"]
