# SPDX-FileCopyrightText: 2023 Shun Sakai
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

[target.aarch64-unknown-linux-musl]
pre-build = ["apt-get update && apt-get install -y asciidoctor"]

[target.arm-unknown-linux-musleabihf]
pre-build = ["apt-get update && apt-get install -y asciidoctor"]

[target.armv7-unknown-linux-musleabihf]
pre-build = ["apt-get update && apt-get install -y asciidoctor"]

[target.x86_64-unknown-linux-musl]
pre-build = ["apt-get update && apt-get install -y asciidoctor"]
