// SPDX-FileCopyrightText: 2023 Shun Sakai
//
// SPDX-License-Identifier: CC-BY-4.0

= License
:reuse-spec-url: https://reuse.software/spec-3.3/

Copyright (C) 2022 Shun Sakai

. Unless otherwise noted, each file is distributed under the terms of either
  the _Apache License 2.0_ or the _MIT License_.
. Each file related to the command-line utility and some other files are
  distributed under the terms of the _GNU General Public License v3.0 or later_.
. The format specification is distributed under the terms of the _CC0 1.0
  Universal_.
. Some documents are distributed under the terms of the _Creative Commons
  Attribution 4.0 International Public License_.

This project is compliant with version 3.3 of the
{reuse-spec-url}[_REUSE Specification_].

== Apache License 2.0

....
include::example$LICENSES/Apache-2.0.txt[]
....

== MIT License

....
include::example$LICENSES/MIT.txt[]
....

== GNU General Public License v3.0

....
include::example$LICENSES/GPL-3.0-or-later.txt[]
....

== CC0 1.0 Universal

....
include::example$LICENSES/CC0-1.0.txt[]
....

== Creative Commons Attribution 4.0 International Public License

....
include::example$LICENSES/CC-BY-4.0.txt[]
....
