// SPDX-FileCopyrightText: 2023 Shun Sakai
//
// SPDX-License-Identifier: CC-BY-4.0

= Abcrypt Encrypted Data Format
Shun Sakai <sorairolake@protonmail.ch>
// Specify in UTC.
v0.4.0, 2024-12-09
:icons: font
:idprefix:
:idseparator: -
:sectanchors:
:toc: preamble
:stem:
:scrypt-encrypted-data-format: https://www.tarsnap.com/scrypt.html
:ietf-datatracker: https://datatracker.ietf.org
:datatracker-html-doc: {ietf-datatracker}/doc/html
:rfc9106: {datatracker-html-doc}/rfc9106
:rfc7693: {datatracker-html-doc}/rfc7693
:draft-arciszewski-xchacha-03: {datatracker-html-doc}/draft-arciszewski-xchacha-03

abcrypt is a modern file encryption format with the data authenticity. This
document describes the abcrypt encrypted data format.

== Introduction

abcrypt is a modern file encryption format inspired by the
{scrypt-encrypted-data-format}[scrypt encrypted data format]. abcrypt uses
<<argon2>> for key derivation, <<blake2b-512-mac>> for header integrity
checking and <<xchacha20-poly1305>> for encryption.

== Conventions used in this document

[#argon2,reftext=Argon2]
Argon2 is the key derivation function from {rfc9106}[RFC 9106].

[#blake2b-512-mac,reftext=BLAKE2b-512-MAC]
BLAKE2b-512-MAC is the keyed hash function based on BLAKE2 standardized in
{rfc7693}[RFC 7693]. This uses BLAKE2b and always outputs a 64-byte MAC.

[#xchacha20-poly1305,reftext=XChaCha20-Poly1305]
XChaCha20-Poly1305 is the AEAD algorithm from
{draft-arciszewski-xchacha-03}[draft-arciszewski-xchacha-03].

== Format overview

An abcrypt file is composed of two parts: a <<header-format,header>> containing
the required data and a <<file-body,file body>> encrypted with the derived key.

.The structure of the abcrypt encrypted data format
|===
|Offset |Bytes |Description |Detail

|stem:[0]
|stem:[7]
|Magic number ("abcrypt").
|<<magic-number>>

|stem:[7]
|stem:[1]
|Version number.
|<<version-number>>

|stem:[8]
|stem:[4]
|Argon2 type.
|<<argon2-type>>

|stem:[12]
|stem:[4]
|Argon2 version.
|<<argon2-version>>

|stem:[16]
|stem:[4]
|Memory size `m` (`memoryCost`).
|<<argon2-parameters>>

|stem:[20]
|stem:[4]
|Number of iterations `t` (`timeCost`).
|<<argon2-parameters>>

|stem:[24]
|stem:[4]
|Degree of parallelism `p` (`parallelism`).
|<<argon2-parameters>>

|stem:[28]
|stem:[32]
|Salt for <<argon2>>.
|<<salt-for-argon2>>

|stem:[60]
|stem:[24]
|Nonce for <<xchacha20-poly1305>>.
|<<nonce-for-xchacha20-poly1305>>

|stem:[84]
|stem:[64]
|MAC of the header.
|<<header-mac>>

|stem:[148]
|stem:[n]
|Ciphertext.
|<<file-body>>

|stem:[148 + n]
|stem:[16]
|MAC of the ciphertext.
|<<file-body>>
|===

All multibyte values are stored in little-endian.

== Key derivation

The derived key for computing the header MAC and the derived key for encryption
are produced by <<argon2>>.

.The derived key is produced as follows
----
derivedKey = Argon2(
    password = password,
    salt = header[28..60],
    parallelism = header[24..28],
    tagLength = 96,
    memoryCost = header[16..20],
    timeCost = header[20..24],
    version = header[12..16],
    secretKey = [],
    associatedData = [],
    type = header[8..12],
)
----

The size of `secretKey` (pepper) and `associatedData` (associated data) are
zero (empty).

The resulting derived key (`derivedKey`) length is 96 bytes. The first 32 bytes
of `derivedKey` are the <<xchacha20-poly1305>> key (`encryptionKey`) for
encryption, and the last 64 bytes are the <<blake2b-512-mac>> key
(`headerMacKey`) for computing the header MAC.

.The derived key is split as follows
----
encryptionKey = derivedKey[..32]
headerMacKey = derivedKey[32..]
----

<<argon2-type,`type`>>, <<argon2-version,`version`>>,
<<argon2-parameters,`memoryCost`>>, <<argon2-parameters,`timeCost`>>,
<<argon2-parameters,`parallelism`>>, and <<salt-for-argon2,`salt`>> used when
encrypting are stored in the header, and these stored values are used when
decrypting.

== Header format

=== Magic number

A 7-byte string for identifying the abcrypt encrypted data format. The value is
"abcrypt" (`61 62 63 72 79 70 74` in hex).

=== Version number

A 1-byte version number of the abcrypt encrypted data format. The current value
is 1.

=== Argon2 type

.The following Argon2 types are valid
|===
|Value |Description

|stem:[0]
|Argon2d.

|stem:[1]
|Argon2i.

|stem:[2]
|Argon2id.
|===

The Argon2 type is represented as 4 bytes in little-endian.

=== Argon2 version

.The following Argon2 versions are valid
|===
|Value |Description

|stem:[16]
|Version 0x10 (16 in decimal).

|stem:[19]
|Version 0x13 (19 in decimal).
|===

The Argon2 version is represented as 4 bytes in little-endian.

=== Argon2 parameters

.Argon2 has the following parameters that control
|===
|Parameter |Minimum value |Maximum value |Description

|`memoryCost`
|stem:[8 xx p]
|stem:[2^(32) - 1]
|Memory size in KiB.

|`timeCost`
|stem:[1]
|stem:[2^(32) - 1]
|Number of iterations.

|`parallelism`
|stem:[1]
|stem:[2^(24) - 1]
|Degree of parallelism.
|===

Each parameter is represented as 4 bytes in little-endian.

=== Salt for Argon2

A 32-byte salt for <<argon2>>.

NOTE: The salt should be generated from a CSPRNG.

=== Nonce for XChaCha20-Poly1305

A 24-byte nonce for <<xchacha20-poly1305>>.

NOTE: The nonce should be generated from a CSPRNG.

=== Header MAC

The MAC (authentication tag) of the header. The MAC is computed with
<<blake2b-512-mac>> over the whole header up to and including the nonce (first
84 bytes of the header).

.The MAC is computed as follows
----
mac = BLAKE2b(
    data = header[..84],
    digestLength = 64,
    key = headerMacKey,
    salt = [],
    personalization = [],
)
----

The size of `salt` and `personalization` (personalization string) are zero
(empty).

== File body

The file body is encrypted with XChaCha20-Poly1305.

.The ciphertext is computed as follows
----
ciphertext = XChaCha20-Poly1305(
    plaintext = plaintext,
    aad = [],
    key = encryptionKey,
    nonce = header[60..84],
)
----

The size of `aad` (additional authenticated data) is zero (empty).

<<nonce-for-xchacha20-poly1305,`nonce`>> used when encrypting is stored in the
header, and the stored value is used when decrypting.

IMPORTANT: The abcrypt encrypted data format uses a postfix tag.

== Filename extension

abcrypt files should use the extension `.abcrypt`.

== MIME type

When transferring abcrypt files over the Internet, the appropriate MIME type is
`application/x-abcrypt`.

== ABNF definition of the file format

[source,abnf]
----
ifdef::site-gen-antora[]
include::example$abcrypt.abnf[lines=5..-1]
endif::[]
ifndef::site-gen-antora[]
include::abcrypt.abnf[lines=5..-1]
endif::[]
----

== Format changelog

Version 1::

  * Add the Argon2 type field to allow choosing the Argon2 type.
  * Add the Argon2 version field to allow choosing the Argon2 version.

Version 0::

  * Initial release.
