# SPDX-FileCopyrightText: 2023 Shun Sakai
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "abcrypt-cli"
version = "0.5.1"
edition.workspace = true
rust-version.workspace = true
description = "A command-line utility for encrypt and decrypt files"
homepage.workspace = true
repository.workspace = true
license = "GPL-3.0-or-later"
keywords = ["abcrypt"]
categories = ["command-line-utilities"]
include = ["/LICENSES", "/README.md", "/src"]

[[bin]]
name = "abcrypt"
path = "src/main.rs"

[dependencies]
abcrypt = { path = "../abcrypt", version = "0.5.0", features = ["serde"] }
anyhow.workspace = true
byte-unit = "5.2.0"
clap = { workspace = true, features = ["wrap_help"] }
clap_complete = "4.5.66"
clap_complete_nushell = "4.5.10"
dialoguer.workspace = true
serde_json = { version = "1.0.149", optional = true }
sysexits = "0.12.0"

[dev-dependencies]
assert_cmd = "2.1.2"
predicates = "3.1.4"

[features]
default = ["json"]
json = ["dep:serde_json"]

[lints]
workspace = true
