# SPDX-FileCopyrightText: 2023 Shun Sakai
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

[tool.bumpversion]
current_version = "0.5.0"

[[tool.bumpversion.files]]
glob = "docs/man/man3/*.3.adoc"

[[tool.bumpversion.files]]
filename = "examples/meson.build"

[[tool.bumpversion.files]]
filename = "examples/version.hpp"

[[tool.bumpversion.files]]
filename = "src/lib.rs"
