# SPDX-FileCopyrightText: 2023 Shun Sakai
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

[tool.bumpversion]
current_version = "0.4.0"

[[tool.bumpversion.files]]
filename = "docs/spec/FORMAT.adoc"

[[tool.bumpversion.files]]
filename = "src/lib.rs"
