// SPDX-FileCopyrightText: 2022 Shun Sakai
//
// SPDX-License-Identifier: CC-BY-4.0

= rscrypt-dec(1)
// Specify in UTC.
:docdate: 2023-07-17
:doctype: manpage
ifdef::revnumber[:mansource: rscrypt {revnumber}]
:manmanual: General Commands Manual
:includedir: ../include

== NAME

rscrypt-dec - decrypt files

== SYNOPSIS

*rscrypt dec* [_OPTION_]... _INFILE_ [_OUTFILE_]

== DESCRIPTION

This command decrypt files.

== POSITIONAL ARGUMENTS

_INFILE_::

  Input file. If "-" is specified, data will be read from stdin.

_OUTFILE_::

  Output file. If _OUTFILE_ is not specified, the result will be write to
  stdout.

== OPTIONS

*-f*, *--force*::

  Force the decryption to proceed even if it requires an excessive amount of
  resources.

*-M*, *--max-memory* _BYTE_::

  Use at most the specified bytes of RAM to compute the derived key. _BYTE_ can
  also be provided as bytes with the unit symbol (such as MiB and GB). _BYTE_
  should be between 1 MiB and 16 EiB.

*-m*, *--max-memory-fraction* _RATE_::

  Use at most the specified fraction of the available RAM to compute the
  derived key. _RATE_ can be provided as a decimal or a fraction. _RATE_ should
  be greater than 0 and less than or equal to *0.5*. Default is 0.5.

*-t*, *--max-time* _DURATION_::

  Use at most the specified duration of CPU time to compute the derived key.
  Default is 300 seconds.

*--passphrase-from-tty*::

  Read the password from /dev/tty. This is the default behavior.

*--passphrase-from-stdin*::

  Read the password from stdin.

*--passphrase-from-env* _VAR_::

  Read the password from the environment variable. Note that storing a password
  in an environment variable can be a security risk.

*--passphrase-from-file* _FILE_::

  Read the password from the file. Note that storing a password in a file can
  be a security risk.

*-v*, *--verbose*::

  Print encryption parameters and resource limits.

*-h*, *--help*::

  Print help information.

*-V*, *--version*::

  Print version information.

include::{includedir}/section-exit-status.adoc[]

include::{includedir}/section-notes.adoc[]

== EXAMPLES

Decrypt a file:{blank}::

  $ *rscrypt dec file.enc file*

include::{includedir}/section-reporting-bugs.adoc[]

include::{includedir}/section-copyright.adoc[]

== SEE ALSO

*rscrypt*(1), *rscrypt-enc*(1), *rscrypt-help*(1), *rscrypt-info*(1),
*scrypt*(1)
