# SPDX-FileCopyrightText: 2023 Shun Sakai
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

[package]
name = "abcrypt-py"
version = "0.3.0"
edition.workspace = true
rust-version.workspace = true
description = "Python bindings for abcrypt"
homepage.workspace = true
repository.workspace = true
license = "Apache-2.0 OR MIT"
keywords = ["abcrypt", "crypto"]
categories = ["cryptography"]
include = ["/LICENSES", "/README.md", "/src"]
publish = false

[lib]
crate-type = ["cdylib", "rlib"]
name = "abcrypt_py"

[dependencies]
abcrypt = { path = "../abcrypt", version = "0.5.0" }
pyo3 = "0.28.2"

[lints]
workspace = true
