# SPDX-FileCopyrightText: 2024 Shun Sakai
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

[project]
name = "abcrypt-py"
requires-python = ">=3.10"
classifiers = [
  "License :: OSI Approved :: Apache Software License",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Rust",
]
dynamic = ["version"]

[project.urls]
Changelog = "https://github.com/sorairolake/abcrypt/blob/develop/crates/python/CHANGELOG.adoc"
Documentation = "https://sorairolake.github.io/abcrypt/book/python/index.html"
Issues = "https://github.com/sorairolake/abcrypt/issues"
Repository = "https://github.com/sorairolake/abcrypt"

[dependency-groups]
dev = ["pytest>=9.0.2", "ruff>=0.14.14", "ty>=0.0.14"]

[build-system]
requires = ["maturin>=1.4,<2.0"]
build-backend = "maturin"

[tool.maturin]
features = ["pyo3/extension-module"]

[tool.ruff]
line-length = 79

[tool.ruff.lint]
ignore = [
  "E501",
  "D100",
  "D103",
  "D203",
  "D212",
  "S101",
  "COM812",
  "ISC001",
  "INP001",
  "T201",
  "PT011",
  "PLR2004",
]
select = ["ALL"]

[tool.ruff.format]
docstring-code-format = true
line-ending = "lf"
