// SPDX-FileCopyrightText: 2022 Shun Sakai
//
// SPDX-License-Identifier: CC-BY-4.0

= abcrypt-information(1)
// Specify in UTC.
:docdate: 2025-05-11
:revnumber: 0.4.0
:doctype: manpage
:mansource: abcrypt {revnumber}
:manmanual: General Commands Manual
ifndef::site-gen-antora[:includedir: ./include]
:ietf-datatracker: https://datatracker.ietf.org
:datatracker-html-doc: {ietf-datatracker}/doc/html
:rfc9106: {datatracker-html-doc}/rfc9106

== NAME

abcrypt-information - provides information about the encryption parameters

== SYNOPSIS

*abcrypt information* [_OPTION_]... [_FILE_]

== DESCRIPTION

This command provides information about the encryption parameters from _FILE_.
If _FILE_ is not specified, data will be read from standard input.

The encryption parameters outputs either a human-readable string or JSON.

.List of the encryption parameters
|===
|Parameter |Description

|`m` (`memoryCost`)
|The memory size in KiB

|`t` (`timeCost`)
|The number of iterations

|`p` (`parallelism`)
|The degree of parallelism
|===

The encryption parameters represents the same thing as the Argon2 parameters as
defined in {rfc9106}[RFC 9106].

*abcrypt info* and *abcrypt i* are aliases for this command.

== POSITIONAL ARGUMENTS

_FILE_::

  Input file. If _FILE_ is not specified, data will be read from standard input.

== OPTIONS

*-j*, *--json*::

  Output the encryption parameters as JSON. This option is available if the
  `json` feature is enabled at compile time.

*-h*, *--help*::

  Print help message. The short flag (*-h*) will print a condensed help message
  while the long flag (*--help*) will print a detailed help message.

*-V*, *--version*::

  Print version number. The long flag (*--version*) will also print the
  copyright notice, the license notice and where to report bugs.

ifndef::site-gen-antora[include::{includedir}/section-exit-status.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-exit-status.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-notes.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-notes.adoc[]]

== EXAMPLES

Print the encryption parameters:{blank}::

  $ *abcrypt information data.txt.abcrypt*

Print the encryption parameters as JSON:{blank}::

  $ *abcrypt information -j data.txt.abcrypt*

ifndef::site-gen-antora[include::{includedir}/section-reporting-bugs.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-reporting-bugs.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-copyright.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-copyright.adoc[]]

== SEE ALSO

*abcrypt*(1), *abcrypt-argon2*(1), *abcrypt-completion*(1),
*abcrypt-decrypt*(1), *abcrypt-encrypt*(1), *abcrypt-help*(1)
