// SPDX-FileCopyrightText: 2022 Shun Sakai
//
// SPDX-License-Identifier: CC-BY-4.0

= abcrypt-information(1)
// Specify in UTC.
:docdate: 2024-04-15
:doctype: manpage
ifdef::revnumber[:mansource: abcrypt {revnumber}]
ifndef::revnumber[:mansource: abcrypt]
:manmanual: General Commands Manual
ifndef::site-gen-antora[:includedir: ./include]

== NAME

abcrypt-information - provides information about the encryption parameters

== SYNOPSIS

*abcrypt information* [_OPTION_]... [_FILE_]

== DESCRIPTION

This command provides information about the encryption parameters. The result
will be write to stdout.

*abcrypt info* and *abcrypt i* are aliases for this command.

== POSITIONAL ARGUMENTS

_FILE_::

  Input file. If _FILE_ is not specified, data will be read from stdin.

== OPTIONS

ifdef::json,env-github,site-gen-antora[]
*-j*, *--json*::

  Output the encryption parameters as JSON.
endif::[]

*-h*, *--help*::

  Print help message. The short flag (*-h*) will print a condensed help message
  while the long flag (*--help*) will print a detailed help message.

*-V*, *--version*::

  Print version number. The long flag (*--version*) will also print the
  copyright notice, the license notice and where to report bugs.

ifndef::site-gen-antora[include::{includedir}/section-exit-status.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-exit-status.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-notes.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-notes.adoc[]]

== EXAMPLES

Print the encryption parameters:{blank}::

  $ *abcrypt information data.txt.abcrypt*

ifdef::json,env-github,site-gen-antora[]
Print the encryption parameters as JSON:{blank}::

  $ *abcrypt information -j data.txt.abcrypt*
endif::[]

ifndef::site-gen-antora[include::{includedir}/section-reporting-bugs.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-reporting-bugs.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-copyright.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-copyright.adoc[]]

== SEE ALSO

*abcrypt*(1), *abcrypt-decrypt*(1), *abcrypt-encrypt*(1), *abcrypt-help*(1)
