// SPDX-FileCopyrightText: 2022 Shun Sakai
//
// SPDX-License-Identifier: CC-BY-4.0

= abcrypt-encrypt(1)
// Specify in UTC.
:docdate: 2024-08-01
:doctype: manpage
ifdef::revnumber[:mansource: abcrypt {revnumber}]
ifndef::revnumber[:mansource: abcrypt]
:manmanual: General Commands Manual
ifndef::site-gen-antora[:includedir: ./include]

== NAME

abcrypt-encrypt - encrypt files

== SYNOPSIS

*abcrypt encrypt* [_OPTION_]... [_FILE_]

== DESCRIPTION

This command encrypts _FILE_. By default, the result will be write to stdout.
If _FILE_ is not specified, data will be read from stdin. If *-o* is specified,
the result will be write to the specified file.

The passphrase used for encryption can be read from either `/dev/tty`, stdin,
an environment variable, or a file.

*abcrypt enc* and *abcrypt e* are aliases for this command.

== POSITIONAL ARGUMENTS

_FILE_::

  Input file. If _FILE_ is not specified, data will be read from stdin.

== OPTIONS

*-o*, *--output* _FILE_::

  Output the result to a file.

*-m*, *--memory-cost* _BYTE_::

  Set the memory size in bytes. _BYTE_ can be suffixed with the symbol (B) and
  the byte prefix (such as Ki and M). If only a numeric value is specified for
  _BYTE_, it is the same as specifying the symbol without the byte prefix. Note
  that _BYTE_ that is not multiples of 1 KiB is truncated toward zero to the
  nearest it. _BYTE_ should be between *8 KiB* and *4294967295 KiB* (4 TiB).
  Default is 19456 KiB (19 MiB).

*-t*, *--time-cost* _NUM_::

  Set the number of iterations. _NUM_ should be between *1* and *4294967295*.
  Default is 2.

*-p*, *--parallelism* _NUM_::

  Set the degree of parallelism. _NUM_ should be between *1* and *16777215*.
  Default is 1.

*--passphrase-from-tty*::

  Read the passphrase from `/dev/tty`. This is the default behavior.

*--passphrase-from-stdin*::

  Read the passphrase from stdin. This option cannot be used if _FILE_ is also
  stdin.

*--passphrase-from-tty-once*::

  Read the passphrase from `/dev/tty` only once.

*--passphrase-from-env* _VAR_::

  Read the passphrase from the environment variable. Note that storing a
  passphrase in an environment variable can be a security risk.

*--passphrase-from-file* _FILE_::

  Read the passphrase from the file. Note that storing a passphrase in a file
  can be a security risk.

*-v*, *--verbose*::

  Print the encryption parameters.

*-h*, *--help*::

  Print help message. The short flag (*-h*) will print a condensed help message
  while the long flag (*--help*) will print a detailed help message.

*-V*, *--version*::

  Print version number. The long flag (*--version*) will also print the
  copyright notice, the license notice and where to report bugs.

ifndef::site-gen-antora[include::{includedir}/section-exit-status.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-exit-status.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-notes.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-notes.adoc[]]

== EXAMPLES

Encrypt a file:{blank}::

  $ *abcrypt encrypt data.txt > data.txt.abcrypt*

Output the result to the specified file:{blank}::

  $ *abcrypt encrypt -o data.txt.abcrypt data.txt*

Encrypt a file with the specified parameters:{blank}::

  $ *abcrypt encrypt -m 32KiB -t 3 -p 4 data.txt > data.txt.abcrypt*

Read the passphrase from the file:{blank}::

  $ *abcrypt encrypt --passphrase-from-file passphrase.txt data.txt > data.txt.abcrypt*

Print the encryption parameters when encrypting:{blank}::

  $ *abcrypt encrypt -v data.txt > data.txt.abcrypt*

ifndef::site-gen-antora[include::{includedir}/section-reporting-bugs.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-reporting-bugs.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-copyright.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-copyright.adoc[]]

== SEE ALSO

*abcrypt*(1), *abcrypt-decrypt*(1), *abcrypt-help*(1), *abcrypt-information*(1)
