// SPDX-FileCopyrightText: 2023 Shun Sakai
//
// SPDX-License-Identifier: CC-BY-4.0

= abcrypt-help(1)
// Specify in UTC.
:docdate: 2023-08-23
:doctype: manpage
ifdef::revnumber[:mansource: abcrypt {revnumber}]
ifndef::revnumber[:mansource: abcrypt]
:manmanual: General Commands Manual
ifndef::site-gen-antora[:includedir: ./include]

== NAME

abcrypt-help - print the help for a command

== SYNOPSIS

*abcrypt help* [_COMMAND_]

== DESCRIPTION

This command prints the help for a command.

This command is identical to any of the following:{blank}::

  $ *abcrypt* [_COMMAND_] *-h*|*--help*

== POSITIONAL ARGUMENTS

_COMMAND_::

  Subcommand to print the help.

ifndef::site-gen-antora[include::{includedir}/section-exit-status.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-exit-status.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-notes.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-notes.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-reporting-bugs.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-reporting-bugs.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-copyright.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-copyright.adoc[]]

== SEE ALSO

*abcrypt*(1), *abcrypt-decrypt*(1), *abcrypt-encrypt*(1),
*abcrypt-information*(1)
