// SPDX-FileCopyrightText: 2022 Shun Sakai
//
// SPDX-License-Identifier: CC-BY-4.0

= abcrypt-decrypt(1)
// Specify in UTC.
:docdate: 2024-04-15
:doctype: manpage
ifdef::revnumber[:mansource: abcrypt {revnumber}]
ifndef::revnumber[:mansource: abcrypt]
:manmanual: General Commands Manual
:includedir: ./include

== NAME

abcrypt-decrypt - decrypt files

== SYNOPSIS

*abcrypt decrypt* [_OPTION_]... [_FILE_]

== DESCRIPTION

This command decrypt files. By default, the result will be write to stdout.

*abcrypt dec* and *abcrypt d* are aliases for this command.

== POSITIONAL ARGUMENTS

_FILE_::

  Input file. If _FILE_ is not specified, data will be read from stdin.

== OPTIONS

*-o*, *--output* _FILE_::

  Output the result to a file.

*--passphrase-from-tty*::

  Read the passphrase from /dev/tty. This is the default behavior.

*--passphrase-from-stdin*::

  Read the passphrase from stdin. This option cannot be used if _FILE_ is also
  stdin.

*--passphrase-from-env* _VAR_::

  Read the passphrase from the environment variable. Note that storing a
  passphrase in an environment variable can be a security risk.

*--passphrase-from-file* _FILE_::

  Read the passphrase from the file. Note that storing a passphrase in a file
  can be a security risk.

*-v*, *--verbose*::

  Print the encryption parameters.

*-h*, *--help*::

  Print help message. The short flag (*-h*) will print a condensed help message
  while the long flag (*--help*) will print a detailed help message.

*-V*, *--version*::

  Print version number. The long flag (*--version*) will also print the
  copyright notice, the license notice and where to report bugs.

include::{includedir}/section-exit-status.adoc[]

include::{includedir}/section-notes.adoc[]

== EXAMPLES

Decrypt a file:{blank}::

  $ *abcrypt decrypt data.txt.abcrypt > data.txt*

Output the result to the specified file:{blank}::

  $ *abcrypt decrypt -o data.txt data.txt.abcrypt*

Read the passphrase from the file:{blank}::

  $ *abcrypt decrypt --passphrase-from-file passphrase.txt data.txt.abcrypt > data.txt*

Print the encryption parameters when decrypting:{blank}::

  $ *abcrypt decrypt -v data.txt.abcrypt > data.txt*

include::{includedir}/section-reporting-bugs.adoc[]

include::{includedir}/section-copyright.adoc[]

== SEE ALSO

*abcrypt*(1), *abcrypt-encrypt*(1), *abcrypt-help*(1), *abcrypt-information*(1)
