// SPDX-FileCopyrightText: 2022 Shun Sakai
//
// SPDX-License-Identifier: CC-BY-4.0

= abcrypt(1)
// Specify in UTC.
:docdate: 2024-12-07
:revnumber: 0.3.3
:doctype: manpage
:mansource: abcrypt {revnumber}
:manmanual: General Commands Manual
ifndef::site-gen-antora[:includedir: ./include]

== NAME

abcrypt - an utility for encrypt and decrypt files

== SYNOPSIS

*{manname}* [_OPTION_]... _COMMAND_

== DESCRIPTION

*{manname}* is a command-line utility for encrypt and decrypt files using the
*abcrypt*(5) encrypted data format.

== COMMANDS

*abcrypt-encrypt*(1)::

  Encrypt files.

*abcrypt-decrypt*(1)::

  Decrypt files.

*abcrypt-argon2*(1)::

  Provides information about the Argon2 context.

*abcrypt-information*(1)::

  Provides information about the encryption parameters.

*abcrypt-help*(1)::

  Print the help for a command.

== OPTIONS

*-h*, *--help*::

  Print help message. The short flag (*-h*) will print a condensed help message
  while the long flag (*--help*) will print a detailed help message.

*-V*, *--version*::

  Print version number. The long flag (*--version*) will also print the
  copyright notice, the license notice and where to report bugs.

*--generate-completion* _SHELL_::

  Generate shell completion. The completion is output to standard output.

  The possible values are:{blank}:::

    *bash*::::

      Bash.

    *elvish*::::

      Elvish.

    *fish*::::

      fish.

    *nushell*::::

      Nushell.

    *powershell*::::

      PowerShell.

    *zsh*::::

      Zsh.

ifndef::site-gen-antora[include::{includedir}/section-exit-status.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-exit-status.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-notes.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-notes.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-reporting-bugs.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-reporting-bugs.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-copyright.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-copyright.adoc[]]

== SEE ALSO

*age*(1), *rage*(1), *scrypt*(1)
