// SPDX-FileCopyrightText: 2022 Shun Sakai
//
// SPDX-License-Identifier: CC-BY-4.0

= abcrypt-decrypt(1)
// Specify in UTC.
:docdate: 2025-06-07
:revnumber: 0.5.0
:doctype: manpage
:mansource: abcrypt {revnumber}
:manmanual: General Commands Manual
ifndef::site-gen-antora[:includedir: ./include]

== NAME

abcrypt-decrypt - decrypt files

== SYNOPSIS

*abcrypt decrypt* [_OPTION_]... [_FILE_]

== DESCRIPTION

This command decrypts _FILE_. By default, the result will be write to standard
output. If _FILE_ is not specified, data will be read from standard input. If
*-o* is specified, the result will be write to the specified file.

The passphrase used for decryption can be read from either `/dev/tty`, standard
input, an environment variable, or a file.

== POSITIONAL ARGUMENTS

_FILE_::

  Input file. If _FILE_ is not specified, data will be read from standard input.

== OPTIONS

*-o*, *--output* _FILE_::

  Output the result to a file.

*--passphrase-from-tty*::

  Read the passphrase from `/dev/tty`. This is the default behavior.

*--passphrase-from-stdin*::

  Read the passphrase from standard input. This option cannot be used if _FILE_
  is also standard input.

*--passphrase-from-env* _VAR_::

  Read the passphrase from the environment variable. Note that storing a
  passphrase in an environment variable can be a security risk.

*--passphrase-from-file* _FILE_::

  Read the passphrase from the file. Note that storing a passphrase in a file
  can be a security risk.

*-v*, *--verbose*::

  Print the encryption parameters.

*-h*, *--help*::

  Print help message. The short flag (*-h*) will print a condensed help message
  while the long flag (*--help*) will print a detailed help message.

*-V*, *--version*::

  Print version number.

ifndef::site-gen-antora[include::{includedir}/section-exit-status.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-exit-status.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-notes.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-notes.adoc[]]

== EXAMPLES

Decrypt a file:{blank}::

  $ *abcrypt decrypt data.txt.abcrypt > data.txt*

Output the result to the specified file:{blank}::

  $ *abcrypt decrypt -o data.txt data.txt.abcrypt*

Read the passphrase from the file:{blank}::

  $ *abcrypt decrypt --passphrase-from-file passphrase.txt data.txt.abcrypt > data.txt*

Print the encryption parameters when decrypting:{blank}::

  $ *abcrypt decrypt -v data.txt.abcrypt > data.txt*

ifndef::site-gen-antora[include::{includedir}/section-reporting-bugs.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-reporting-bugs.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-copyright.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-copyright.adoc[]]

== SEE ALSO

*abcrypt*(1), *abcrypt-argon2*(1), *abcrypt-completion*(1),
*abcrypt-encrypt*(1), *abcrypt-information*(1)
