// SPDX-FileCopyrightText: 2024 Shun Sakai
//
// SPDX-License-Identifier: CC-BY-4.0

= abcrypt_error_message_out_len(3)
// Specify in UTC.
:docdate: 2024-04-13
:revnumber: 0.4.0
:doctype: manpage
:mansource: abcrypt-capi {revnumber}
:manmanual: Library Functions Manual
ifndef::site-gen-antora[:includedir: ./include]

== NAME

abcrypt_error_message_out_len - API function

== SYNOPSIS

[source,c]
----
#include <abcrypt.h>

uintptr_t abcrypt_error_message_out_len(enum abcrypt_error_code error_code);
----

== DESCRIPTION

This function returns the number of output bytes of the error message.

=== Arguments

_error_code_::

  An error value defined in *abcrypt_error_code*(3).

== RETURN VALUE

Returns the number of output bytes of the error message.

== VERSIONS

This function was added in version 0.1.0.

ifndef::site-gen-antora[include::{includedir}/section-reporting-bugs.adoc[]]
ifdef::site-gen-antora[include::partial$man/man3/include/section-reporting-bugs.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-copyright.adoc[]]
ifdef::site-gen-antora[include::partial$man/man3/include/section-copyright.adoc[]]

== SEE ALSO

*abcrypt_error_message*(3)
