// SPDX-FileCopyrightText: 2024 Shun Sakai
//
// SPDX-License-Identifier: CC-BY-4.0

= abcrypt_error_code(3)
// Specify in UTC.
:docdate: 2024-12-07
:revnumber: 0.4.0
:doctype: manpage
:mansource: abcrypt-capi {revnumber}
:manmanual: Library Functions Manual
ifndef::site-gen-antora[:includedir: ./include]

== NAME

abcrypt_error_code - API type

== SYNOPSIS

[source,c]
----
#include <abcrypt.h>

typedef enum abcrypt_error_code {
  ABCRYPT_ERROR_CODE_OK,
  ABCRYPT_ERROR_CODE_ERROR,
  ABCRYPT_ERROR_CODE_INVALID_LENGTH,
  ABCRYPT_ERROR_CODE_INVALID_MAGIC_NUMBER,
  ABCRYPT_ERROR_CODE_UNSUPPORTED_VERSION,
  ABCRYPT_ERROR_CODE_UNKNOWN_VERSION,
  ABCRYPT_ERROR_CODE_INVALID_ARGON2_TYPE,
  ABCRYPT_ERROR_CODE_INVALID_ARGON2_VERSION,
  ABCRYPT_ERROR_CODE_INVALID_ARGON2_PARAMS,
  ABCRYPT_ERROR_CODE_INVALID_ARGON2_CONTEXT,
  ABCRYPT_ERROR_CODE_INVALID_HEADER_MAC,
  ABCRYPT_ERROR_CODE_INVALID_MAC,
} abcrypt_error_code;
----

== DESCRIPTION

This type represents the error code for the abcrypt encrypted data format.

=== Variants

_ABCRYPT_ERROR_CODE_OK_::

  Everything is ok.

_ABCRYPT_ERROR_CODE_ERROR_::

  General error.

_ABCRYPT_ERROR_CODE_INVALID_LENGTH_::

  The encrypted data was shorter than 164 bytes.

_ABCRYPT_ERROR_CODE_INVALID_MAGIC_NUMBER_::

  The magic number (file signature) was invalid.

_ABCRYPT_ERROR_CODE_UNSUPPORTED_VERSION_::

  The version was the unsupported abcrypt version number.

_ABCRYPT_ERROR_CODE_UNKNOWN_VERSION_::

  The version was the unrecognized abcrypt version number.

_ABCRYPT_ERROR_CODE_INVALID_ARGON2_TYPE_::

  The Argon2 type were invalid.

_ABCRYPT_ERROR_CODE_INVALID_ARGON2_VERSION_::

  The Argon2 version were invalid.

_ABCRYPT_ERROR_CODE_INVALID_ARGON2_PARAMS_::

  The Argon2 parameters were invalid.

_ABCRYPT_ERROR_CODE_INVALID_ARGON2_CONTEXT_::

  The Argon2 context was invalid.

_ABCRYPT_ERROR_CODE_INVALID_HEADER_MAC_::

  The MAC (authentication tag) of the header was invalid.

_ABCRYPT_ERROR_CODE_INVALID_MAC_::

  The MAC (authentication tag) of the ciphertext was invalid.

== VERSIONS

This type was added in version 0.1.0.

ifndef::site-gen-antora[include::{includedir}/section-reporting-bugs.adoc[]]
ifdef::site-gen-antora[include::partial$man/man3/include/section-reporting-bugs.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-copyright.adoc[]]
ifdef::site-gen-antora[include::partial$man/man3/include/section-copyright.adoc[]]

== SEE ALSO

*abcrypt_error_message*(3), *abcrypt_error_message_out_len*(3)
