// SPDX-FileCopyrightText: 2024 Shun Sakai
//
// SPDX-License-Identifier: CC-BY-4.0

= abcrypt_params_read(3)
// Specify in UTC.
:docdate: 2024-04-13
:doctype: manpage
:icons: font
ifdef::revnumber[:mansource: abcrypt-capi {revnumber}]
ifndef::revnumber[:mansource: abcrypt-capi]
:manmanual: Library Functions Manual
ifndef::site-gen-antora[:includedir: ./include]

== NAME

abcrypt_params_read - API function

== SYNOPSIS

[source,c]
----
#include <abcrypt.h>

enum abcrypt_error_code abcrypt_params_read(uint8_t *ciphertext,
                                            uintptr_t ciphertext_len,
                                            struct abcrypt_params *params);
----

== DESCRIPTION

This function reads the Argon2 parameters.

=== Arguments

_ciphertext_::

  A pointer to the ciphertext to read.

_ciphertext_len_::

  Length of _ciphertext_.

_params_::

  A pointer to the Argon2 parameters structure to write to.

CAUTION: Behavior is undefined if _ciphertext_ or _ciphertext_len_ is invalid.

== RETURN VALUE

Returns `ABCRYPT_ERROR_CODE_OK` if successful, otherwise returns an error value
defined in *abcrypt_error_code*(3).

== VERSIONS

This function was added in version 0.1.0.

ifndef::site-gen-antora[include::{includedir}/section-reporting-bugs.adoc[]]
ifdef::site-gen-antora[include::partial$man/man3/include/section-reporting-bugs.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-copyright.adoc[]]
ifdef::site-gen-antora[include::partial$man/man3/include/section-copyright.adoc[]]

== SEE ALSO

*abcrypt_params_memory_cost*(3), *abcrypt_params_parallelism*(3),
*abcrypt_params_read*(3), *abcrypt_params_time_cost*(3)
