// SPDX-FileCopyrightText: 2024 Shun Sakai
//
// SPDX-License-Identifier: CC-BY-4.0

= abcrypt_params_memory_cost(3)
// Specify in UTC.
:docdate: 2024-04-13
:revnumber: 0.3.2
:doctype: manpage
:mansource: abcrypt-capi {revnumber}
:manmanual: Library Functions Manual
ifndef::site-gen-antora[:includedir: ./include]

== NAME

abcrypt_params_memory_cost - API function

== SYNOPSIS

[source,c]
----
#include <abcrypt.h>

uint32_t abcrypt_params_memory_cost(struct abcrypt_params *params);
----

== DESCRIPTION

This function gets memory size in KiB.

=== Arguments

_params_::

  A pointer to the Argon2 parameters structure.

== RETURN VALUE

Returns `0` if `params` is `NULL`, otherwise returns the memory size in KiB.

== VERSIONS

This function was added in version 0.3.0.

ifndef::site-gen-antora[include::{includedir}/section-reporting-bugs.adoc[]]
ifdef::site-gen-antora[include::partial$man/man3/include/section-reporting-bugs.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-copyright.adoc[]]
ifdef::site-gen-antora[include::partial$man/man3/include/section-copyright.adoc[]]

== SEE ALSO

*abcrypt_params_read*(3)
