// SPDX-FileCopyrightText: 2024 Shun Sakai
//
// SPDX-License-Identifier: CC-BY-4.0

= abcrypt_params_free(3)
// Specify in UTC.
:docdate: 2024-04-13
:revnumber: 0.5.0
:doctype: manpage
:icons: font
:mansource: abcrypt-capi {revnumber}
:manmanual: Library Functions Manual
ifndef::site-gen-antora[:includedir: ./include]

== NAME

abcrypt_params_free - API function

== SYNOPSIS

[source,c]
----
#include <abcrypt.h>

void abcrypt_params_free(struct abcrypt_params *params);
----

== DESCRIPTION

This function frees the Argon2 parameters structure.

=== Arguments

_params_::

  A pointer to the Argon2 parameters structure to free.

WARNING: This function must not be called on a freed _params_, because a
double-free may occur.

== RETURN VALUE

Returns nothing.

== VERSIONS

This function was added in version 0.1.0.

ifndef::site-gen-antora[include::{includedir}/section-reporting-bugs.adoc[]]
ifdef::site-gen-antora[include::partial$man/man3/include/section-reporting-bugs.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-copyright.adoc[]]
ifdef::site-gen-antora[include::partial$man/man3/include/section-copyright.adoc[]]

== SEE ALSO

*abcrypt_params*(3)
