// SPDX-FileCopyrightText: 2023 Shun Sakai
//
// SPDX-License-Identifier: Apache-2.0 OR MIT

= Abcrypt Encrypted Data Format
Shun Sakai <sorairolake@protonmail.ch>
// Specify in UTC.
v0.2.7, 2023-09-30
:icons: font
:idprefix:
:idseparator: -
:sectanchors:
:toc: preamble
:stem:
:scrypt-encrypted-data-format: https://www.tarsnap.com/scrypt.html
:ietf-datatracker: https://datatracker.ietf.org
:datatracker-html-doc: {ietf-datatracker}/doc/html
:rfc9106: {datatracker-html-doc}/rfc9106
:rfc7693: {datatracker-html-doc}/rfc7693
:draft-arciszewski-xchacha-03: {datatracker-html-doc}/draft-arciszewski-xchacha-03

abcrypt is a modern file encryption format with the data authenticity. This
document describes the abcrypt encrypted data format.

== Introduction

abcrypt is a modern file encryption format inspired by the
{scrypt-encrypted-data-format}[scrypt encrypted data format]. abcrypt uses
<<argon2,Argon2id>> for key derivation, <<blake2b-512-mac>> for header
integrity checking and <<xchacha20-poly1305>> for encryption.

== Conventions used in this document

[#argon2,reftext=Argon2]
Argon2 is the key derivation function from {rfc9106}[RFC 9106].

[#blake2b-512-mac,reftext=BLAKE2b-512-MAC]
BLAKE2b-512-MAC is the keyed hash function based on BLAKE2 standardized in
{rfc7693}[RFC 7693]. This uses BLAKE2b and always outputs a 64-byte MAC.

[#xchacha20-poly1305,reftext=XChaCha20-Poly1305]
XChaCha20-Poly1305 is the AEAD algorithm from
{draft-arciszewski-xchacha-03}[draft-arciszewski-xchacha-03].

== Format overview

An abcrypt file is composed of two parts: a <<header-format,header>> containing
the required data and a <<file-body,file body>> encrypted with the derived key.

abcrypt files may use the extension `.abcrypt`.

.The structure of the abcrypt format
|===
|Offset |Bytes |Description |Detail

|stem:[0]
|stem:[7]
|Magic number ("abcrypt").
|<<header-format>>

|stem:[7]
|stem:[1]
|Version number.
|<<version-number>>

|stem:[8]
|stem:[4]
|Memory size `m`.
|<<argon2-parameters>>

|stem:[12]
|stem:[4]
|Number of iterations `t`.
|<<argon2-parameters>>

|stem:[16]
|stem:[4]
|Degree of parallelism `p`.
|<<argon2-parameters>>

|stem:[20]
|stem:[32]
|Salt.
|<<salt>>

|stem:[52]
|stem:[24]
|Nonce.
|<<nonce>>

|stem:[76]
|stem:[64]
|MAC of the header.
|<<header-mac>>

|stem:[140]
|stem:[n]
|Ciphertext.
|<<file-body>>

|stem:[140 + n]
|stem:[16]
|MAC of the ciphertext.
|<<file-body>>
|===

All multibyte values are stored in little-endian.

== Key derivation

The derived key for computing the header MAC and the derived key for encryption
are produced by <<argon2>>. The abcrypt format uses Argon2id as the type and
0x13 (19) as the version.

.The derived key is produced as follows
----
derived_key = Argon2(
    m_cost = header[8..12],
    t_cost = header[12..16],
    p_cost = header[16..20],
    output_len = 96,
    algorithm = Argon2id,
    version = 0x13,
    pwd = password,
    salt = header[20..52],
)
----

The resulting derived key (`derived_key`) length is 96 bytes. The first 32
bytes of `derived_key` are for encryption (<<xchacha20-poly1305>> key), and the
last 64 bytes are for computing the header MAC (<<blake2b-512-mac>> key).

<<argon2-parameters,`m_cost`>>, <<argon2-parameters,`t_cost`>>,
<<argon2-parameters,`p_cost`>>, and <<salt,`salt`>> used when encrypting are
stored in the header, and these stored values are used when decrypting.

== Header format

=== Magic number

A 7-byte string for identifying the abcrypt format. The value is "abcrypt"
(`61 62 63 72 79 70 74` in hex).

=== Version number

A 1-byte version number of the abcrypt format. The current value is 0.

=== Argon2 parameters

.Argon2 has the following parameters that control
|===
|Parameter |Minimum value |Maximum value |Description

|`m_cost`
|stem:[8 xx p]
|stem:[2^(32) - 1]
|Memory size in KiB.

|`t_cost`
|stem:[1]
|stem:[2^(32) - 1]
|Number of iterations.

|`p_cost`
|stem:[1]
|stem:[2^(24) - 1]
|Degree of parallelism.
|===

Each parameter is represented as 4 bytes in little-endian.

=== Salt

A 32-byte salt for <<argon2>>.

NOTE: The salt should be generated from a CSPRNG.

=== Nonce

A 24-byte nonce for <<xchacha20-poly1305>>.

NOTE: The nonce should be generated from a CSPRNG.

=== Header MAC

The MAC (authentication tag) of the header. The MAC is computed with
<<blake2b-512-mac>> over the whole header up to and including the nonce (first
76 bytes of the header).

.The MAC is computed as follows
----
mac = BLAKE2b(
    data = header[..76],
    output_size = 64,
    key = derived_key[32..],
    salt = [],
    person = [],
)
----

The size of `salt` and `person` (personalization string) is zero (empty).

== File body

The file body is encrypted with XChaCha20-Poly1305.

.The ciphertext is computed as follows
----
ciphertext = XChaCha20-Poly1305(
    key = derived_key[..32],
    nonce = header[20..52],
    plaintext = plaintext,
    aad = [],
)
----

The size of `aad` (additional authenticated data) is zero (empty).

IMPORTANT: The abcrypt format uses a postfix tag.

== Format changelog

Version 0::

  Initial release.
