# SPDX-FileCopyrightText: 2023 Shun Sakai
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

[package]
name = "abcrypt-wasm"
version = "0.5.0"
edition.workspace = true
rust-version.workspace = true
description = "Wasm bindings for abcrypt"
homepage.workspace = true
repository.workspace = true
license = "Apache-2.0 OR MIT"
keywords = ["abcrypt", "crypto"]
categories = ["cryptography", "wasm"]
include = ["/LICENSES", "/README.md", "/src"]
publish = false

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["--enable-bulk-memory", "--enable-nontrapping-float-to-int"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
abcrypt = { path = "../abcrypt", version = "0.5.0" }
getrandom = { version = "0.2.16", features = ["js"] }
wasm-bindgen = "0.2.105"

[dev-dependencies]
wasm-bindgen-test = "0.3.55"

[lints]
workspace = true
